### ISSUE TITLE
Document and improve webservice

### ISSUE THREAD

**Issue by pezholio** [theodi/csvlint#158]
I've had a crack at documenting the webservice here:

https://github.com/theodi/csvlint/wiki/Webservice

But there are still improvements to be made. Mainly that the validations get created in the background, so the user will have to keep polling until the validation is created.

**Comment by ldodds** [comment]
Should we also look at alignment with OKFN's Good Tables? Supporting the same API might be helpful for people moving between the two services.

I've not looked at it in detail though to see if there are any specific pros/cons.

**Comment by quadrophobiac** [comment]
I'll do a quick comparison of GoodTables and CSVlint as the two services currently stand
