### ISSUE TITLE
Database running out of space

### ISSUE THREAD

**Issue by pezholio** [theodi/csvlint#169]
We currently pay for a 5GB instance on http://www.objectrocket.com/, but we're fast running out of space. We currently pay $190 a month - to up to a 20GB instance would cost $500

**Comment by pezholio** [comment]
https://github.com/theodi/csvlint/pull/196 is now live, and I've created the indexes on the box, so files should now die after 24 hours, which should mean much less space being wasted

**Comment by danielgavrilov** [comment]
We've just realised in #196 the TTL index was only set up for the Validations, which means GridFs files won't be deleted in 24 hours. Very sorry about this. 

Might be best to revert to @bcouston's [latest commit](https://github.com/theodi/csvlint/commit/1775833715a3b6ed8c3cc0b5c62aa72c7650c11d), and make the `clean_up` task execute itself after 24 hours, as was the initial plan?

**Comment by pezholio** [comment]
Ah, I see. So it deletes the validations, but not the underlying GridFS files?

**Comment by pezholio** [comment]
We could probably monkey patch `Mongoid::GridFs` to add the index?

**Comment by quadrophobiac** [comment]
is monkey patch downloading a local file and amending the class therein, or creating a class that inherits from ```Mongoid::GridFs```?

**Comment by pezholio** [comment]
Yeah, inheriting is the best thing to do

**Comment by pezholio** [comment]
Something like:

```
class CSVlint::File < Mongoid::GridFs
  index({expirable_created_at: 1}, {expire_after_seconds: 24.hours})

  .. other logic goes here ...
end
```

**Comment by quadrophobiac** [comment]
I was trying just that but to little avail

**Comment by pezholio** [comment]
Oh, that sucks. Would seem like that would work. Might be worth having a cursory glance over the `Mongoid::GridFs` repo - https://github.com/ahoward/mongoid-grid_fs

**Comment by quadrophobiac** [comment]
ok, that was the plan and you think it would work - so maybe attacking it along those lines is the resolution to this issue, rather than reopening the old issue?

**Comment by pezholio** [comment]
Cool, sounds sensible :+1:

**Comment by quadrophobiac** [comment]
We're doing some research and we're not convinced this is a better solution that the one (periodic runner than empties the DB) which James and Ben worked on (ironically). Can this be parked until Monday and a discussion with @Floppy and others around the next sprint can transpire?

**Comment by pezholio** [comment]
Yup, sounds like a plan :+1:

**Comment by quadrophobiac** [comment]
Cool - I think it's either go back to the previous solution, or replace the GridFS as the means of storing the temp files - it looks like a hard problem to delete the GridFS by TTL because the chunks to not have a date field

**Comment by pezholio** [comment]
I'm a gonna close this. Think the issue is now fixed.
