### ISSUE TITLE
Let people know how to give feedback or help to the project

### ISSUE THREAD

**Issue by CharlesNepote** [theodi/csvlint#172]
On the website http://csvlint.io/ why not provide a link to the github repository, where people could give feedback (issues) or help with code?

**Comment by scrybbler** [comment]
I agree. it's pretty quiet here.

**Comment by Floppy** [comment]
We really should - thanks for the reminder! One good way is to join #theodi on irc.freenode.net and come and say Hi.

I'll see if I can add some contribution guidelines this week!

**Comment by quadrophobiac** [comment]
@CharlesNepote & @scrybbler I appreciate that what I'm about to offer is the **coldest** of cold coffee BUT the readme and [ODI Toolbox Wiki](https://github.com/theodi/toolbox/wiki/) have both been recently established to address just the concerns you flagged many years ago. We've also set up a [feature roadmap](https://trello.com/b/2xc7Q0kd/labs-public-toolbox-roadmap?menu=filter&filter=label:CSVlint) for all of our open data tools, including CSVlint. If you're still interested in CSVlint it would be great to have your input!
