### ISSUE TITLE
Should report row numbers on data errors

### ISSUE THREAD

**Issue by scrybbler** [theodi/csvlint#182]
The tool doesn't report row numbers on data errors. "The data in column 7 is inconsistent with others values in the same column" is too vague when you may have hundreds of rows. It's like going to a doctor for a checkup, and he says, "You've got cancer somewhere in the upper half of your body!"

Maybe row-by-row problem identification is outside the scope of this project, but for us it is a dealbreaker. If CSVLint is already doing full validation, it has the data and merely needs to record and report it. (I make it sound so easy, don't I? Ha... we users are so ungrateful.)

Enclosing screenshot of validations results page, CSV, and schema.

![csv lint validation results](https://cloud.githubusercontent.com/assets/12719803/7945397/fb89966e-0935-11e5-8dba-2e06124d743b.png)

**Comment by scrybbler** [comment]
Links to CSV and schema respectively:

https://drive.google.com/file/d/0B3CDKorSOdGNNm1CbXFrUmlFY1U/view?usp=sharing
https://drive.google.com/file/d/0B3CDKorSOdGNN3JlZ2pDLWNKaXc/view?usp=sharing

**Comment by ldodds** [comment]
csvlint does report row numbers, but as noted in #183 the schema is not being applied correctly so you're not seeing the expected results. Using the corrected schema at https://gist.githubusercontent.com/ldodds/b0ae664e623ec62f595c/raw/ce3180b10cf187903aed3df501aeac2fdd2d06be/fixed-schema.json

I get the following:

![screenshot from 2015-06-02 21 36 51](https://cloud.githubusercontent.com/assets/109082/7946610/83b5f404-096f-11e5-8fcf-937797a6b4f6.png)

**Comment by scrybbler** [comment]
Nice. Clearly not an issue so I am closing this ticket...!
