### ISSUE TITLE
Maxlength constraint (in schema) not working

### ISSUE THREAD

**Issue by scrybbler** [theodi/csvlint#184]
Here are my csv and schema respectively:
https://drive.google.com/file/d/0B3CDKorSOdGNNm1CbXFrUmlFY1U/view?usp=sharing
https://drive.google.com/file/d/0B3CDKorSOdGNN3JlZ2pDLWNKaXc/view?usp=sharing

The required constraint is violated on line 13 (column 1) 
of the data.

The validator reports no errors or warnings on that data column.

![csv lint validation results](https://cloud.githubusercontent.com/assets/12719803/7945832/cf70682a-0938-11e5-80be-7e4266b53c66.png)

**Comment by ldodds** [comment]
See comment on #183, there are some issues in the schema which means its not being applied

**Comment by scrybbler** [comment]
Closed - schema error.
