### ISSUE TITLE
Remove all the Marshaling

### ISSUE THREAD

**Issue by Floppy** [theodi/csvlint#191]
Marshalling objects into the DB is not a good plan. We should find a better way to do whatever this was intended to do.

**Comment by pezholio** [comment]
I think this is a lazy way of storing the validation result returned by csvlint.rb. I can't see any reason why we can't be a bit smarter and save the results as, say an embedded Mongo object.

**Comment by Floppy** [comment]
Yeah, it was a shortcut. However, it has started to break things so we might need to be cleverer.

**Comment by quadrophobiac** [comment]
Closing this as AFAICT these changes have been part of codebase for sometime
