### ISSUE TITLE
Can't validate files over about 700k

### ISSUE THREAD

**Issue by pezholio** [theodi/csvlint#201]
Just trying a few things out, and I get a 413 error when trying to validate any file over 700kb. Suspect this is because nginx doesn't have `client_max_body_size` set anywhere (the default is 1mb - so I'm not sure why 700kb seems to be the limit). We should probably set this to a more sensible maximum, like 5mb?

**Comment by pikesley** [comment]
Fixed with [this](https://github.com/theodi/chef-csvlint/blob/master/attributes/default.rb#L8)
