### ISSUE TITLE
Pre tags render even when the 'content' attribute is missing

### ISSUE THREAD

**Issue by quadrophobiac** [theodi/csvlint#207]
![screen shot 2015-08-06 at 09 56 50](https://cloud.githubusercontent.com/assets/1039017/9107725/91907ad8-3c21-11e5-8a75-ecaeed5e7f3b.png)
In the above the pre tags are rendering irrespective of whether there is content or not, this should be a simple amendment to the partial rendering logic

**Comment by bcouston** [comment]
Opened PR #210

**Comment by bcouston** [comment]
Closed by PR #210
