### ISSUE TITLE
Uploading large files causes 500 chunks error at 100%

### ISSUE THREAD

**Issue by bcouston** [theodi/csvlint#224]
On uploading a large CSV file (13.8MB), the progress bar reaches 100%, however after waiting around for a bit, a 500 error occurs:

![screen shot 2015-09-09 at 16 08 26](https://cloud.githubusercontent.com/assets/9949074/9765886/4ebbb724-570e-11e5-832f-140ee4cd7be7.png)

With another error upon validation.

![screen shot 2015-09-09 at 16 09 06](https://cloud.githubusercontent.com/assets/9949074/9765895/50884b80-570e-11e5-9b5d-7187aeefdaac.png)

**Comment by bcouston** [comment]
Unable to replicate this in development.

**Comment by pezholio** [comment]
![](http://cdn2.hubspot.net/hub/228391/file-745508197-jpg/blog-files/devopsevil.jpg)

**Comment by pezholio** [comment]
I've increased the load balancer timeout to 60 seconds, which fixes the issue. However the last POST request seems to be taking an inordinate amount of time, so this might need some investigation, as it seems to the user that the upload is getting 'stuck' at 100%
