### ISSUE TITLE
Return more results per page in Recent Validations or offer data download

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/csvlint#253]
I was looking through the [Recent Validations](http://csvlint.io/validation.html?page=308) page to try find organisations in Queensland who are using CSVLint.

Only 7 results are returned per page and I wasn't prepared to scroll through 309 pages, so I gave up.

Consider returning more results per page or, better still, allowing the data to be downloaded.

**Comment by pezholio** [comment]
Good call - we do have a JSON representation that you can use, but it's paginated too http://csvlint.io/validation.json

We'll look at maybe providing a download option, so you can download all validations as CSV (valid of course!)

You might also find the statistics page interesting too - http://csvlint.io/statistics

**Comment by Stephen-Gates** [comment]
@pezholio thanks for the changes. Json download works but I get, "Service Unavailable - The service is temporarily unavailable. Please try again later." on CSV download.

**Comment by pezholio** [comment]
@Stephen-Gates - should all be sorted now! :+1:

**Comment by Stephen-Gates** [comment]
@pezholio working now! 

Nine Australian Government agencies have had datasets validated with CSVLint and interestingly, some commercial and personal use. ~50% valid. 

Thanks again.
