### ISSUE TITLE
Show number of rows processed on Validation Results page

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/csvlint#261]
Provide confidence that the whole file was processed especially when you use the "Validate Again" button and the CSV behind the URL may have changed in size.

Important to know if processing completed or a large file size resulted in only part of the file being processed. Especially given the [warning](http://csvlint.io/about#warning) on the /About page
![validateagain](https://cloud.githubusercontent.com/assets/9379524/13623858/54bfe89a-e5f5-11e5-8bb7-adc546667c50.PNG)

![goodtables](https://cloud.githubusercontent.com/assets/9379524/13625280/c33ae3d6-e601-11e5-927a-1627597a9e5b.PNG)

**Comment by quadrophobiac** [comment]
this is a small fix that is currently stalled due to below
- [  ]  resolve CSVlint .env to run locally without problems noted in #281
with planned additions of
- [  ] write tests for stress test fixtures (multiples of 1000 rows and 1MB and 10MB file size)
