### ISSUE TITLE
Why not validate csvy files?

### ISSUE THREAD

**Issue by CharlesNepote** [theodi/csvlint#277]
For the moment csvlint doesn't validate csvy files ([example](http://csvlint.io/validation/585cf7d8333339000400001e)).

csvy is an effort to simplify data description and control:

- metadata is in YAML format
- metadata is published inside the csv file

See [http://csvy.org](http://csvy.org) for more information.

Note: csvy is using JSON Table Schema semantic (which is already recognized by csvlint).

**Comment by Floppy** [comment]
Ah, interesting, using Jekyll-style YAML frontmatter. Not seen that before, that might be worth incuding. Thanks!

**Comment by quadrophobiac** [comment]
Hi Charles - I think this feature request is better filed against the CSVlint library https://github.com/theodi/csvlint.rb/

**Comment by quadrophobiac** [comment]
This issue was moved to theodi/csvlint.rb#203
